<a href="https://colab.research.google.com/github/leandroleao2k/ImageML/blob/main/RegrasDeAssociacao%20Apriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Como descobrir regras a priori com conjunto de items
## o algoritmo sera usado apriori do mlxtent

In [1]:
import numpy as np
import pandas as pd

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

dataset = [['bread', 'milk', 'eggs'],
           ['bread', 'milk', 'coke'],
           ['beer', 'coke'],
           ['beer','bread', 'milk', 'eggs']]

## Transformação das transações

In [4]:
tenc = TransactionEncoder()
tenc.fit(dataset)
dataset_enc = tenc.transform(dataset)

print(tenc.columns_)
print(tenc.columns_mapping_)
print(dataset_enc.astype(int))
dataset_enc

['beer', 'bread', 'coke', 'eggs', 'milk']
{'beer': 0, 'bread': 1, 'coke': 2, 'eggs': 3, 'milk': 4}
[[0 1 0 1 1]
 [0 1 1 0 1]
 [1 0 1 0 0]
 [1 1 0 1 1]]


array([[False,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True, False, False],
       [ True,  True, False,  True,  True]])

In [6]:
df = pd.DataFrame(dataset_enc, columns=tenc.columns_)
df

beer  bread   coke   eggs   milk
0  False   True  False   True   True
1  False   True   True  False   True
2   True  False   True  False  False
3   True   True  False   True   True

## Gerando conjunto de items frequentes com apriori 

In [7]:
min_support = 0.5
frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)
frequent_itemsets

support             itemsets
0     0.50               (beer)
1     0.75              (bread)
2     0.50               (coke)
3     0.50               (eggs)
4     0.75               (milk)
5     0.50        (bread, eggs)
6     0.75        (bread, milk)
7     0.50         (milk, eggs)
8     0.50  (bread, milk, eggs)

### testando com 0.7 de min support

In [8]:
min_support = 0.7
frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)
frequent_itemsets

support       itemsets
0     0.75        (bread)
1     0.75         (milk)
2     0.75  (bread, milk)